//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filmy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Filmy()
        {
            this.Seanse = new HashSet<Seanse>();
        }
    
        public int FilmID { get; set; }
        public string Tytul { get; set; }
        public string Rezyser { get; set; }
        public int RokWydania { get; set; }
        public string Obsada { get; set; }
        public string Opis { get; set; }
        public decimal Ocena { get; set; }
        public byte[] Zdjecie { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seanse> Seanse { get; set; }
    }
}
