//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RezerwacjeMiejsca
    {
        public int RezerwacjaMiejsceID { get; set; }
        public Nullable<int> RezerwacjaID { get; set; }
        public int Rzad { get; set; }
        public int Miejsce { get; set; }
    
        public virtual Rezerwacje Rezerwacje { get; set; }
    }
}
