//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seanse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seanse()
        {
            this.Rezerwacje = new HashSet<Rezerwacje>();
        }
    
        public int SeansID { get; set; }
        public Nullable<int> FilmID { get; set; }
        public System.DateTime DataSeansu { get; set; }
        public Nullable<int> SalaID { get; set; }
    
        public virtual Filmy Filmy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezerwacje> Rezerwacje { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
